### PR TITLE
Dylan cron servlet final

### PR DESCRIPTION
**Pull request by dylanzika**

### CODE REVIEW

**Comment by kelseyball** [comment]
I added a VoteBatchCounter class that keeps track of the number of fake vote batches and  objectifying it, so now you can get the number of batches by:

VoteBatchCounter counter = ofy().load().type(VoteBatchCounter.class).first().getValue();
int numBatches = counter.getNumBatches();

**Comment by dylanzika** [comment]
Awwwwwsome !!!!

Sincerely,

Dylan Zika

**Comment by reedcozartut** [comment]
can this pull request be resolved?

**Comment by williammills** [comment]
I thought Dylan said yesterday that it broke when combined with Kelsey's branch (which was already merged)

**Pull request closed without merging**
